using Fluxora.Application.Common;
using Fluxora.Application.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Fluxora.Api.Controllers;

/// <summary>
/// Read-only: receivables/payables are generated by Sales/Purchasing approval. Payment/receipt
/// application lives in PaymentsController/ReceiptsController; this exposes the resulting state
/// plus the cash movement ledger they produce.
/// </summary>
[ApiController]
[Authorize(Policy = AppPolicies.FinanceAccess)]
[Route("api")]
public class FinanceController(FinanceQueryService financeQueryService) : ControllerBase
{
    [HttpGet("receivables")]
    public async Task<ActionResult<IReadOnlyList<ReceivableDto>>> ListReceivables(
        [FromQuery] int page = 1, [FromQuery] int pageSize = 25, CancellationToken cancellationToken = default)
    {
        pageSize = Math.Clamp(pageSize, 1, 100);
        return Ok(await financeQueryService.ListReceivablesAsync(page, pageSize, cancellationToken));
    }

    [HttpGet("receivables/{id:guid}")]
    public async Task<ActionResult<ReceivableDto>> GetReceivable(Guid id, CancellationToken cancellationToken)
    {
        try
        {
            return Ok(await financeQueryService.GetReceivableByIdAsync(id, cancellationToken));
        }
        catch (NotFoundException)
        {
            return NotFound();
        }
    }

    [HttpGet("payables")]
    public async Task<ActionResult<IReadOnlyList<PayableDto>>> ListPayables(
        [FromQuery] int page = 1, [FromQuery] int pageSize = 25, CancellationToken cancellationToken = default)
    {
        pageSize = Math.Clamp(pageSize, 1, 100);
        return Ok(await financeQueryService.ListPayablesAsync(page, pageSize, cancellationToken));
    }

    [HttpGet("payables/{id:guid}")]
    public async Task<ActionResult<PayableDto>> GetPayable(Guid id, CancellationToken cancellationToken)
    {
        try
        {
            return Ok(await financeQueryService.GetPayableByIdAsync(id, cancellationToken));
        }
        catch (NotFoundException)
        {
            return NotFound();
        }
    }

    [HttpGet("cash-movements")]
    public async Task<ActionResult<IReadOnlyList<CashMovementDto>>> ListCashMovements(
        [FromQuery] int page = 1, [FromQuery] int pageSize = 25, CancellationToken cancellationToken = default)
    {
        pageSize = Math.Clamp(pageSize, 1, 100);
        return Ok(await financeQueryService.ListCashMovementsAsync(page, pageSize, cancellationToken));
    }
}
