using Fluxora.Application.Common;
using Fluxora.Domain.Finance;

namespace Fluxora.Application.Finance;

/// <summary>
/// Read-only access to receivables/payables generated by Sales/Purchasing approval. Payment
/// application against these installments (with idempotency and concurrency guarantees) is
/// Milestone 3 scope.
/// </summary>
public class FinanceQueryService(IReceivableRepository receivableRepository, IPayableRepository payableRepository)
{
    public async Task<IReadOnlyList<ReceivableDto>> ListReceivablesAsync(
        int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var receivables = await receivableRepository.ListAsync(page, pageSize, cancellationToken);
        return receivables.Select(FinanceMapper.ToDto).ToList();
    }

    public async Task<ReceivableDto> GetReceivableByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var receivable = await receivableRepository.GetByIdAsync(id, cancellationToken)
            ?? throw new NotFoundException(nameof(Receivable), id);
        return FinanceMapper.ToDto(receivable);
    }

    public async Task<IReadOnlyList<PayableDto>> ListPayablesAsync(
        int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var payables = await payableRepository.ListAsync(page, pageSize, cancellationToken);
        return payables.Select(FinanceMapper.ToDto).ToList();
    }

    public async Task<PayableDto> GetPayableByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var payable = await payableRepository.GetByIdAsync(id, cancellationToken)
            ?? throw new NotFoundException(nameof(Payable), id);
        return FinanceMapper.ToDto(payable);
    }
}
