using Fluxora.Application.Common;
using Fluxora.Domain.Finance;

namespace Fluxora.Application.Finance;

/// <summary>
/// Read-only access to receivables/payables generated by Sales/Purchasing approval, and the
/// cash movement ledger produced by payment/receipt application.
/// </summary>
public class FinanceQueryService(
    IReceivableRepository receivableRepository, IPayableRepository payableRepository, ICashMovementRepository cashMovementRepository)
{
    public async Task<IReadOnlyList<ReceivableDto>> ListReceivablesAsync(
        int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var receivables = await receivableRepository.ListAsync(page, pageSize, cancellationToken);
        return receivables.Select(FinanceMapper.ToDto).ToList();
    }

    public async Task<ReceivableDto> GetReceivableByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var receivable = await receivableRepository.GetByIdAsync(id, cancellationToken)
            ?? throw new NotFoundException(nameof(Receivable), id);
        return FinanceMapper.ToDto(receivable);
    }

    public async Task<IReadOnlyList<PayableDto>> ListPayablesAsync(
        int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var payables = await payableRepository.ListAsync(page, pageSize, cancellationToken);
        return payables.Select(FinanceMapper.ToDto).ToList();
    }

    public async Task<PayableDto> GetPayableByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var payable = await payableRepository.GetByIdAsync(id, cancellationToken)
            ?? throw new NotFoundException(nameof(Payable), id);
        return FinanceMapper.ToDto(payable);
    }

    public async Task<IReadOnlyList<CashMovementDto>> ListCashMovementsAsync(
        int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var movements = await cashMovementRepository.ListAsync(page, pageSize, cancellationToken);
        return movements.Select(m => new CashMovementDto(
            m.Id, m.OccurredAtUtc, m.Direction.ToString(), m.Amount, m.ReferenceType, m.ReferenceId)).ToList();
    }
}
